from fastapi import APIRouter, Depends, HTTPException, status, Query
from sqlalchemy.orm import Session
from typing import List, Optional
from datetime import datetime, timedelta
from app.config.database import get_db, get_payments_db
from app.models import APIKey, User, Subscription, UsageLog
from app.models.payments import PaymentTransaction
from app.api.schemas import APIKeyCreate, APIKeyResponse
from app.utils import generate_api_key
from app.middleware.auth import get_current_user

router = APIRouter(prefix="/api-keys", tags=["api-keys"])


@router.get("/", response_model=List[APIKeyResponse])
def list_api_keys(
    db: Session = Depends(get_db),
    current_user: User = Depends(get_current_user)
):
    # Admin can see all keys, users only their own
    if current_user.is_superuser:
        return db.query(APIKey).all()
    return db.query(APIKey).filter(APIKey.user_id == current_user.id).all()


@router.get("/marketplace", response_model=List[APIKeyResponse])
def list_available_paid_keys(
    category: Optional[str] = Query(None),
    db: Session = Depends(get_db),
    current_user: User = Depends(get_current_user)
):
    # Keys pre-generated by admin that are not yet assigned to a user
    # Now includes both Paid and Free keys that are "In Marketplace" (user_id is None)
    query = db.query(APIKey).filter(APIKey.user_id == None)
    if category:
        query = query.filter(APIKey.category == category)
    return query.all()


@router.post("/buy/{key_id}", response_model=APIKeyResponse)
def buy_api_key(
    key_id: int,
    db: Session = Depends(get_db),
    pdb: Session = Depends(get_payments_db),
    current_user: User = Depends(get_current_user)
):
    api_key = db.query(APIKey).filter(APIKey.id == key_id, APIKey.user_id == None).first()
    if not api_key:
        raise HTTPException(status_code=404, detail="Key not available")

    # Only enforce subscription and payment for PAID keys
    if api_key.is_paid:
        # Admin bypass for subscription check
        if not current_user.is_superuser:
            # Check if user has an active, non-free subscription
            subscription = db.query(Subscription).filter(
                Subscription.user_id == current_user.id,
                Subscription.status == "active"
            ).first()

            if not subscription or subscription.plan.price_monthly == 0:
                raise HTTPException(status_code=403, detail="Active paid subscription required to access marketplace keys")

        # Process payment (recorded in separate payment DB)
        transaction = PaymentTransaction(
            user_id=current_user.id,
            amount=api_key.price,
            item_type="api_key",
            item_id=api_key.id,
            transaction_id=f"txn_key_{api_key.id}_{int(datetime.utcnow().timestamp())}"
        )
        pdb.add(transaction)
        pdb.commit()

    # Assign the key to the user (Works for both Free and Paid)
    api_key.user_id = current_user.id
    api_key.is_active = True

    # LOG THIS AS USAGE
    usage_log = UsageLog(
        api_key_id=api_key.id,
        user_id=current_user.id,
        endpoint="KEY_ACQUISITION",
        method="PURCHASE",
        status_code=200,
        response_time_ms=0,
        ip_address="system"
    )
    db.add(usage_log)

    # Standard expiry for all obtained keys
    if not api_key.expires_at:
        api_key.expires_at = datetime.utcnow() + timedelta(days=365)

    db.commit()
    db.refresh(api_key)
    return api_key


@router.post("/", response_model=APIKeyResponse, status_code=status.HTTP_201_CREATED)
async def create_api_key(
    api_key_data: APIKeyCreate,
    user_id: Optional[int] = Query(None), # Optional target user ID for admin
    db: Session = Depends(get_db),
    current_user: User = Depends(get_current_user)
):
    import urllib.parse
    import httpx
    if api_key_data.upstream_url:
        parsed = urllib.parse.urlparse(api_key_data.upstream_url)
        if not all([parsed.scheme, parsed.netloc]):
            raise HTTPException(status_code=400, detail="Invalid upstream URL. Must include scheme and host.")
        try:
            # Basic URL validation and reachability check
            async with httpx.AsyncClient() as client:
                res = await client.head(api_key_data.upstream_url, timeout=5.0)
                # We don't strictly require 200, just that the host is reachable
        except Exception as e:
            raise HTTPException(status_code=400, detail=f"Invalid or unreachable upstream URL: {str(e)}")

    # if not current_user.is_superuser:
    #     raise HTTPException(status_code=403, detail="Only administrators can create API keys")

    # LOGIC:
    # 1. If target user_id is provided, use it.
    # 2. If no target user_id and it's PAID, it's a Marketplace Key (user_id = None).
    # 3. If no target user_id and it's FREE, it's the Admin's private key (user_id = current_user.id).

    uid = user_id
    if uid is None:
        if not api_key_data.is_paid:
            uid = current_user.id

    api_key = APIKey(
        key=generate_api_key(),
        name=api_key_data.name,
        category=api_key_data.category,
        upstream_url=api_key_data.upstream_url,
        upstream_key=api_key_data.upstream_key,
        user_id=uid,
        is_paid=api_key_data.is_paid,
        price=api_key_data.price if api_key_data.is_paid else 0.0,
        rate_limit_per_minute=api_key_data.rate_limit_per_minute,
        rate_limit_per_day=api_key_data.rate_limit_per_day
    )

    if api_key_data.expires_at:
        api_key.expires_at = api_key_data.expires_at

    db.add(api_key)
    db.commit()
    db.refresh(api_key)

    return api_key


@router.put("/{api_key_id}/toggle", response_model=APIKeyResponse)
def toggle_api_key(
    api_key_id: int,
    db: Session = Depends(get_db),
    current_user: User = Depends(get_current_user)
):
    query = db.query(APIKey).filter(APIKey.id == api_key_id)
    if not current_user.is_superuser:
        query = query.filter(APIKey.user_id == current_user.id)

    api_key = query.first()
    
    if not api_key:
        raise HTTPException(status_code=404, detail="API key not found")

    api_key.is_active = not api_key.is_active
    db.commit()
    db.refresh(api_key)
    
    return api_key


@router.post("/{api_key_id}/rotate", response_model=APIKeyResponse)
def rotate_api_key(
    api_key_id: int,
    db: Session = Depends(get_db),
    current_user: User = Depends(get_current_user)
):
    query = db.query(APIKey).filter(APIKey.id == api_key_id)
    if not current_user.is_superuser:
        query = query.filter(APIKey.user_id == current_user.id)

    api_key = query.first()
    
    if not api_key:
        raise HTTPException(status_code=404, detail="API key not found")

    # Store current key as previous
    api_key.previous_key = api_key.key
    api_key.previous_key_expires_at = datetime.utcnow() + timedelta(days=7) # 7-day grace period
    
    # Generate new key
    api_key.key = generate_api_key()
    
    db.commit()
    db.refresh(api_key)

    return api_key


@router.delete("/{api_key_id}", status_code=status.HTTP_204_NO_CONTENT)
def delete_api_key(
    api_key_id: int,
    db: Session = Depends(get_db),
    current_user: User = Depends(get_current_user)
):
    if not current_user.is_superuser:
        raise HTTPException(status_code=403, detail="Only administrators can delete API keys")

    api_key = db.query(APIKey).filter(APIKey.id == api_key_id).first()

    if not api_key:
        raise HTTPException(status_code=404, detail="API key not found")

    db.delete(api_key)
    db.commit()
